manual Makefiles: set LD_PATH to protect from stale installs
Trying to build the manual (make -C manual/manual etex-files) when
your current opan switch is stale (for example, 4.05.0 when working on
the current 4.07.0+dev trunk) results in the following error:

    make[1]: Entering directory '/home/gasche/Prog/ocaml/github-trunk/manual/manual/tutorials'
    Fatal error: cannot load shared library dllunix
    Reason: /home/gasche/.opam/4.05.0/lib/ocaml/stublibs/dllunix.so: undefined symbol: caml_strdup
    Failure when generating coreexamples.tex
    Fatal error: cannot load shared library dllunix
    Reason: /home/gasche/.opam/4.05.0/lib/ocaml/stublibs/dllunix.so: undefined symbol: caml_strdup
    Failure when generating lablexamples.tex
    Fatal error: cannot load shared library dllunix
    Reason: /home/gasche/.opam/4.05.0/lib/ocaml/stublibs/dllunix.so: undefined symbol: caml_strdup
    Failure when generating objectexamples.tex
    Fatal error: cannot load shared library dllunix
    Reason: /home/gasche/.opam/4.05.0/lib/ocaml/stublibs/dllunix.so: undefined symbol: caml_strdup
    Failure when generating moduleexamples.tex
    Fatal error: cannot load shared library dllunix
    Reason: /home/gasche/.opam/4.05.0/lib/ocaml/stublibs/dllunix.so: undefined symbol: caml_strdup
    Failure when generating advexamples.tex
    Fatal error: cannot load shared library dllunix
    Reason: /home/gasche/.opam/4.05.0/lib/ocaml/stublibs/dllunix.so: undefined symbol: caml_strdup
    Failure when generating polymorphism.tex
    make[1]: Leaving directory '/home/gasche/Prog/ocaml/github-trunk/manual/manual/tutorials'

This PR fixes the issue by using Makefile.tools' SET_LD_PATH variable
to set a LD_PATH containing the required build directory's otherlibs/
libraries, instead of looking in an installed path.

(no change entry needed)