typing: Improve location for 'variable in scope'
Use the location of the alias instead of the `_ as 'a` type expression:

    2 | let none: type a. (_ as 'a) option = None
                                 ^
    Error: In this scoped type, variable 'a is reserved for the local type a.

Co-authored-by: Florian Angeletti <florian.angeletti@inria.fr>