Fixed PackageKit / DBus problem
On Ubuntu, the error seen was (Ubuntu bug#953756):

org.freedesktop.DBus.Python.TypeError: TypeError: InstallPackages() takes exactly 4 arguments (3 given)

0install first tried to use the old PackageKit and then switch to the new one if it got an UnknownMethod error. This error has now become InvalidArgs instead.

Reported by Michel Alexandre Salim.