TMC: error if several different calls could be optimized
One reason to error in these ambiguous situations, instead of making
a choice for the user, is that the TMC transformation changes the
evaluation order, delaying the call that is made tailrec to after the
evaluation of all other arguments.

Example:

```
type 'a tree =
| Leaf of 'a
| Node of 'a tree * 'a tree

let[@tail_mod_cons] rec correct_map f = function
| Leaf v -> Leaf (f v)
| Node (left, right) ->
  Node (correct_map f left, (correct_map[@tailcall]) f right)

let[@tail_mod_cons] rec incorrect_map f = function
| Leaf v -> Leaf (f v)
| Node (left, right) ->
  Node (incorrect_map f left, incorrect_map f right)
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: [@tail_mod_cons]: this constructor application may be optimized in several different ways, please disambiguate by adding a [@tailcall] attribute to the call that should be made tail-recursive.
```