Location.show_code_at_location: highlight the code at a given location
This uses the "highligh_dumb" machinery, but is explicitly designed to
not print the location itself. This is for use in the expect-style
tests; the expect-test modification will come in a separate commit,
but it looks as nice as the following:

[%%expect{|
Line _, characters 1-4:
 #bar) -> ();;
  ^^^
Error: Unbound class bar
|}];;