env refactoring: remove the current unit name from some exceptions
This small change of behavior simplifies the internal plumbing of env
by avoiding the need to passes the 'current_unit_name' state to
cmi-checking exceptions -- it allows to separate the cmi/crc logic to
a separate module in a future commit.

We believe that the change does not actually reduce error message
clarity, as the name of the offending unit appears in the location
filename anyway (see how these exceptions are handled by
Location.error_of_printer_file in the error printer).

Before:

    File "a.mli", line 1:
    Error: Unit A imports from B, which uses recursive types.
           The compilation flag -rectypes is required

After:

    File "a.mli", line 1:
    Error: Invalid import of B, which uses recursive types.
           The compilation flag -rectypes is required