Switch to Menhir's simplified error handling strategy.
This involves removing the custom parsing loop in parsing/parse.ml
and instead using the parsing loop provided by MenhirLib. We use
Menhir's so-called "simplified" error-handling strategy (which is
new as of 20201216). This strategy differs from the "legacy"
strategy in two ways:

* It does not read one token too far (so the custom code in
  parsing/parse.ml can be removed).

* If the current state cannot shift or reduce the error token,
  then it just dies, whereas the legacy strategy would pop an
  item off the stack and continue.

The second point impacts some of the syntax error messages produced
by the parser. Popping items off the stack meant forgetting part of
the input that had just been read, and would lead the parser to
produce messages that did not make sense to the user, because there
was no way for the user to tell that the message was relative to an
earlier point in the input. Here is an example:

```
$ more foo.ml
(2 + )
$ ocamlc -c foo.ml
File "foo.ml", line 1, characters 5-6:
1 | (2 + )
         ^
Error: Syntax error: ')' expected
File "foo.ml", line 1, characters 0-1:
1 | (2 + )
    ^
  This '(' might be unmatched
```

With the simplified parsing strategy, a simple "Syntax error" message
is printed. This is arguably better: it may seem less informative,
but it is actually less wrong and less confusing. It is a better basis
for producing better syntax error messages in the future.