partially fix the dune build
asmcomp/debug was removed by #10355

There is still a failure on my machine:

    File "asmcomp/emitaux.mli", line 88, characters 31-55:
    Error: Unbound module Emitenv

asmcomp/mitenv is a .mli-only module that was apprently introduced in #8936.